apiVersion: v1
kind: Secret
metadata:
  name: postgis-secret
  namespace: geoint-demo
  labels:
    app: postgis
type: Opaque
stringData:
  # Demo credentials only. Replace for production.
  POSTGRES_USER: geoint_user
  POSTGRES_PASSWORD: GeointPass!2026
  POSTGRES_DB: geoint_db
---
apiVersion: v1
kind: Secret
metadata:
  name: geoserver-secret
  namespace: geoint-demo
  labels:
    app: geoserver
type: Opaque
stringData:
  # Demo credentials only. Replace for production.
  GEOSERVER_ADMIN_USER: admin
  GEOSERVER_ADMIN_PASSWORD: GeoServerPass!2026
