apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoint-cis-ltm
  namespace: geoint-demo
  annotations:
    kubernetes.io/ingress.class: f5
    cert-manager.io/cluster-issuer: "lab-ca-issuer"
    virtual-server.f5.com/partition: "Common"
    virtual-server.f5.com/balance: "round-robin"
spec:
  ingressClassName: f5
  tls:
    - hosts:
        - geoint-ltm.f5demos.com
      secretName: geoint-ltm-f5demos-com-tls
  rules:
    - host: geoint-ltm.f5demos.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80


