apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoint-nginx-ltm
  namespace: geoint-demo
spec:
  ingressClassName: nginx
  rules:
    - host: geoint-ltm.f5demos.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
---
apiVersion: cis.f5.com/v1
kind: IngressLink
metadata:
  name: geoint-cis-ltm-ingresslink
  namespace: geoint-demo
  annotations:
    # BIG-IP virtual server address (replace for your lab)
    virtual-server.f5.com/partition: "Common"
    virtual-server.f5.com/balance: "round-robin"
spec:
  virtualServerAddress: "10.1.10.110"
  host: geoint-ltm.f5demos.com
  selector:
    matchLabels:
      app: ingresslink

