apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-data-pvc
  namespace: geoint-demo
  labels:
    app: geoserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
