apiVersion: v1
kind: Service
metadata:
  name: geoserver-service
  namespace: geoint-demo
  labels:
    app: geoserver
spec:
  type: ClusterIP
  selector:
    app: geoserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
