apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-registry
  namespace: geoint-demo
  labels:
    app: internal-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-registry
  template:
    metadata:
      labels:
        app: internal-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: registry
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: internal-registry-pvc
