apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-registry-ingress
  namespace: geoint-demo
  labels:
    app: internal-registry
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/client-max-body-size: "0"          # ✅ F5 NIC annotation — 0 = unlimited
    nginx.org/proxy-request-buffering: "off"     # ✅ F5 NIC annotation
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry.geoint-demo.local
      secretName: internal-registry-tls
  rules:
    - host: registry.geoint-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internal-registry-service
                port:
                  number: 5000
