apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-registry-ingress
  namespace: geoint-demo
  labels:
    app: internal-registry
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: registry.geoint-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internal-registry-service
                port:
                  number: 5000
