apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internal-registry-pvc
  namespace: geoint-demo
  annotations:
    nfs.io/storage-path: "registry"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 20Gi }