apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pvc
  namespace: geoint-demo
  labels:
    app: postgis
  annotations:
    nfs.io/storage-path: "postgis"          # ← this is the fix
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 5Gi }