apiVersion: v1
kind: Service
metadata:
  name: postgis-service
  namespace: geoint-demo
  labels:
    app: postgis
spec:
  type: ClusterIP
  selector:
    app: postgis
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
